# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "abbrev-1.1.1" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.1.1.tgz";
        sha512 = "nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==";
      };
    };
    "accepts-1.2.13" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.2.13.tgz";
        sha1 = "e5f1f3928c6d95fd96558c36ec3d9d0de4a6ecea";
      };
    };
    "accepts-1.3.5" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.5.tgz";
        sha1 = "eb777df6011723a3b14e8a72c0805c8e86746bd2";
      };
    };
    "ajv-5.5.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "5.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-5.5.2.tgz";
        sha1 = "73b5eeca3fab653e3d3f9422b341ad42205dc965";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.7.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.7.0.tgz";
        sha512 = "32NDda82rhwD9/JBCCkB+MRYDp0oSvlo2IL6rQWA10PQi7tDUM3eqMSltXmY+Oyl/7N3P3qNtAlv7X0d9bI28w==";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "bindings-1.2.1" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.2.1.tgz";
        sha1 = "14ad6113812d2d37d72e67b4cacb4bb726505f11";
      };
    };
    "bindings-1.3.0" = {
      name = "bindings";
      packageName = "bindings";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bindings/-/bindings-1.3.0.tgz";
        sha512 = "DpLh5EzMR2kzvX1KIlVC0VkC3iZtHKTgdtZ0a3pglBZdaQFjt5S9g9xd1lE+YvXyfd6mtCeRnrUfOLYiTMlNSw==";
      };
    };
    "body-parser-1.18.2" = {
      name = "body-parser";
      packageName = "body-parser";
      version = "1.18.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/body-parser/-/body-parser-1.18.2.tgz";
        sha1 = "87678a19d84b47d859b83199bd59bce222b10454";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "bytes-3.0.0" = {
      name = "bytes";
      packageName = "bytes";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bytes/-/bytes-3.0.0.tgz";
        sha1 = "d32815404d689699f85a4ea4fa8755dd13a96048";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "co-4.6.0" = {
      name = "co";
      packageName = "co";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/co/-/co-4.6.0.tgz";
        sha1 = "6ea6bdf3d853ae54ccb8e47bfa0bf3f9031fb184";
      };
    };
    "combined-stream-1.0.6" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.6.tgz";
        sha1 = "723e7df6e801ac5613113a7e445a9b69cb632818";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "content-disposition-0.5.0" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.0.tgz";
        sha1 = "4284fe6ae0630874639e44e80a418c2934135e9e";
      };
    };
    "content-disposition-0.5.2" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.2.tgz";
        sha1 = "0cf68bb9ddf5f2be7961c3a85178cb85dba78cb4";
      };
    };
    "content-type-1.0.4" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.4.tgz";
        sha512 = "hIP3EEPs8tB9AT1L+NUqtwOAps4mk2Zob89MWXMHjHWg9milF/j4osnnQLXBCBFBk/tvIG/tUc9mOUJiPBhPXA==";
      };
    };
    "cookie-0.1.3" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.1.3.tgz";
        sha1 = "e734a5c1417fce472d5aef82c381cabb64d1a435";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "cross-spawn-async-2.2.5" = {
      name = "cross-spawn-async";
      packageName = "cross-spawn-async";
      version = "2.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn-async/-/cross-spawn-async-2.2.5.tgz";
        sha1 = "845ff0c0834a3ded9d160daca6d390906bb288cc";
      };
    };
    "d-1.0.0" = {
      name = "d";
      packageName = "d";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-1.0.0.tgz";
        sha1 = "754bb5bfe55451da69a58b94d45f4c5b0462d58f";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "depd-1.0.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.0.1.tgz";
        sha1 = "80aec64c9d6d97e65cc2a9caa93c0aa6abf73aaa";
      };
    };
    "depd-1.1.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.1.tgz";
        sha1 = "5783b4e1c459f06fa5ca27f991f3d06e7a310359";
      };
    };
    "depd-1.1.2" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.2.tgz";
        sha1 = "9bcd52e14c097763e749b274c4346ed2e560b5a9";
      };
    };
    "destroy-1.0.3" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.3.tgz";
        sha1 = "b433b4724e71fd8551d9885174851c5fc377e2c9";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "dmp-1.0.0" = {
      name = "dmp";
      packageName = "dmp";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dmp/-/dmp-1.0.0.tgz";
        sha1 = "55bc6493a0fe0bb3e131a73355c14f3029af2b89";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "encodeurl-1.0.2" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.2.tgz";
        sha1 = "ad3ff4c86ec2d029322f5a02c3a9a606c95b3f59";
      };
    };
    "es5-ext-0.10.45" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.45";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.45.tgz";
        sha512 = "FkfM6Vxxfmztilbxxz5UKSD4ICMf5tSpRFtDNtkAhOxZ0EKtX6qwmXNyH/sFyIbX2P/nU5AMiA9jilWsUGJzCQ==";
      };
    };
    "es6-iterator-2.0.3" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.3.tgz";
        sha1 = "a7de889141a05a94b0854403b2d0a0fbfa98f3b7";
      };
    };
    "es6-symbol-3.1.1" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.1.tgz";
        sha1 = "bf00ef4fdab6ba1b46ecb7b629b4c7ed5715cc77";
      };
    };
    "escape-html-1.0.2" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.2.tgz";
        sha1 = "d77d32fa98e38c2f41ae85e9278e0e0e6ba1022c";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.7.0" = {
      name = "etag";
      packageName = "etag";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.7.0.tgz";
        sha1 = "03d30b5f67dd6e632d2945d30d6652731a34d5d8";
      };
    };
    "etag-1.8.1" = {
      name = "etag";
      packageName = "etag";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.8.1.tgz";
        sha1 = "41ae2eeb65efa62268aebfea83ac7d79299b0887";
      };
    };
    "execa-0.2.2" = {
      name = "execa";
      packageName = "execa";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-0.2.2.tgz";
        sha1 = "e2ead472c2c31aad6f73f1ac956eef45e12320cb";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "fast-deep-equal-1.1.0" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-1.1.0.tgz";
        sha1 = "c053477817c86b51daa853c81e059b733d023614";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "finalhandler-0.4.0" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.4.0.tgz";
        sha1 = "965a52d9e8d05d2b857548541fb89b53a2497d9b";
      };
    };
    "finalhandler-1.1.1" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-1.1.1.tgz";
        sha512 = "Y1GUDo39ez4aHAw7MysnUD5JzYX+WaIj8I57kO3aEPT1fFRL4sr7mjei97FgnwhAyyzRYmQZaTHb2+9uZ1dPtg==";
      };
    };
    "findup-sync-0.3.0" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.3.0.tgz";
        sha1 = "37930aa5d816b777c03445e1966cc6790a4c0b16";
      };
    };
    "floorine-0.3.0" = {
      name = "floorine";
      packageName = "floorine";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/floorine/-/floorine-0.3.0.tgz";
        sha1 = "cfc23a889d629a22db04ba4b8ce357012d0f1e70";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.2" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.2.tgz";
        sha1 = "4970498be604c20c005d4f5c23aecd21d6b49099";
      };
    };
    "forwarded-0.1.2" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.2.tgz";
        sha1 = "98c23dab1175657b8c0573e8ceccd91b0ff18c84";
      };
    };
    "fresh-0.3.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.3.0.tgz";
        sha1 = "651f838e22424e7566de161d8358caa199f83d4f";
      };
    };
    "fresh-0.5.2" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.5.2.tgz";
        sha1 = "3d8cadd90d976569fa835ab1f8e4b23a105605a7";
      };
    };
    "fsevents-1.2.4" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-1.2.4.tgz";
        sha512 = "z8H8/diyk76B7q5wg+Ud0+CqzcAF3mBBI/bA5ne5zrRUUIvNkJY//D3BqyH571KuAC4Nr7Rw7CjWX4r0y9DvNg==";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha1 = "1bc936b9e02f4a603fcc222ecf7633d30b8b93b1";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "grunt-known-options-1.1.0" = {
      name = "grunt-known-options";
      packageName = "grunt-known-options";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-known-options/-/grunt-known-options-1.1.0.tgz";
        sha1 = "a4274eeb32fa765da5a7a3b1712617ce3b144149";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.0.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.0.3.tgz";
        sha1 = "ba402c266194f15956ef15e0fcf242993f6a7dfd";
      };
    };
    "http-errors-1.3.1" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.3.1.tgz";
        sha1 = "197e22cdebd4198585e8694ef6786197b91ed942";
      };
    };
    "http-errors-1.6.2" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.2.tgz";
        sha1 = "0a002cc85707192a7e7946ceedc11155f60ec736";
      };
    };
    "http-errors-1.6.3" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.6.3.tgz";
        sha1 = "8b55680bb4be283a0b5bf4ea2e38580be1d9320d";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "iconv-lite-0.4.19" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.4.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.4.19.tgz";
        sha512 = "oTZqweIP51xaGPI4uPa56/Pri/480R+mo7SeU+YETByQNhDG55ycFyNLIgta9vXhILrxXDmF7ZGhqZIcuN0gJQ==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "ipaddr.js-1.0.5" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.0.5.tgz";
        sha1 = "5fa78cf301b825c78abc3042d812723049ea23c7";
      };
    };
    "ipaddr.js-1.6.0" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.6.0.tgz";
        sha1 = "e3fa357b773da619f26e95f049d055c72796f86b";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.3.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.3.1.tgz";
        sha1 = "349a6d44c53a51de89b40805c5d5e59b417d3340";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "lodash-4.17.10" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.10.tgz";
        sha512 = "UejweD1pDoXu+AD825lWwp4ZGtSwgnpZxb3JDViD7StjQz+Nb/6l093lx4OQ0foGWNRoc19mWy7BzL+UAK2iVg==";
      };
    };
    "lru-cache-4.1.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.1.3.tgz";
        sha512 = "fFEhvcgzuIoJVUF8fYr5KR0YqxD238zgObTps31YdADwPPAp82a4M8TrckkWyx7ekNlf9aBcVn81cFwwXngrJA==";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "merge-descriptors-1.0.0" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.0.tgz";
        sha1 = "2169cf7538e1b0cc87fb88e1502d8474bbf79864";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "mime-1.4.1" = {
      name = "mime";
      packageName = "mime";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.4.1.tgz";
        sha512 = "KI1+qOZu5DcW6wayYHSzR/tXKCDC5Om4s1z2QJjDULzLcmf3DvzS7oluY4HCTrc+9FiKmWUgeNLg7W3uIQvxtQ==";
      };
    };
    "mime-db-1.33.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.33.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.33.0.tgz";
        sha512 = "BHJ/EKruNIqJf/QahvxwQZXKygOQ256myeN/Ew+THcAa5q+PjyTTMMeNQC4DZw5AwfvelsUrA6B67NKMqXDbzQ==";
      };
    };
    "mime-types-2.1.18" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.18.tgz";
        sha512 = "lc/aahn+t4/SWV/qcmumYjymLsWfN3ELhpmVuUFjgsORruuZPVSwAQryq+HHGvO/SI2KVX26bx+En+zhM8g8hQ==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "nan-2.10.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.10.0.tgz";
        sha512 = "bAdJv7fBLhWC+/Bls0Oza+mvTaNQtP+1RyhhhvD95pgUJz6XM5IzgmxOkItJ9tkoCiplvAnXI1tNmmUD/eScyA==";
      };
    };
    "nan-2.3.5" = {
      name = "nan";
      packageName = "nan";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.3.5.tgz";
        sha1 = "822a0dc266290ce4cd3a12282ca3e7e364668a08";
      };
    };
    "native-diff-match-patch-0.3.1" = {
      name = "native-diff-match-patch";
      packageName = "native-diff-match-patch";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/native-diff-match-patch/-/native-diff-match-patch-0.3.1.tgz";
        sha1 = "620304151a78171386ed2e2f3db2e7dfd6436707";
      };
    };
    "negotiator-0.5.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.5.3.tgz";
        sha1 = "269d5c476810ec92edbe7b6c2f28316384f9a7e8";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "next-tick-1.0.0" = {
      name = "next-tick";
      packageName = "next-tick";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/next-tick/-/next-tick-1.0.0.tgz";
        sha1 = "ca86d1fe8828169b0120208e3dc8424b9db8342c";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "npm-run-path-1.0.0" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-1.0.0.tgz";
        sha1 = "f5c32bf595fe81ae927daec52e82f8b000ac3c8f";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "open-0.0.5" = {
      name = "open";
      packageName = "open";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-0.0.5.tgz";
        sha1 = "42c3e18ec95466b6bf0dc42f3a2945c3f0cad8fc";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "optparse-1.0.5" = {
      name = "optparse";
      packageName = "optparse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/optparse/-/optparse-1.0.5.tgz";
        sha1 = "75e75a96506611eb1c65ba89018ff08a981e2c16";
      };
    };
    "parseurl-1.3.2" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.2.tgz";
        sha1 = "fc289d4ed8993119460c156253262cdc8de65bf3";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-key-1.0.0" = {
      name = "path-key";
      packageName = "path-key";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-1.0.0.tgz";
        sha1 = "5d53d578019646c0d68800db4e146e6bdc2ac7af";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "proxy-addr-1.0.10" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.0.10.tgz";
        sha1 = "0d40a82f801fc355567d2ecb65efe3f077f121c5";
      };
    };
    "proxy-addr-2.0.3" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-2.0.3.tgz";
        sha512 = "jQTChiCJteusULxjBp8+jftSQE5Obdl3k4cnmLA6WXtK6XFuWRnvVL7aCiBqaLPM8c4ph0S4tKna8XvmIwEnXQ==";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "qs-4.0.0" = {
      name = "qs";
      packageName = "qs";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-4.0.0.tgz";
        sha1 = "c31d9b74ec27df75e543a86c78728ed8d4623607";
      };
    };
    "qs-6.5.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.1.tgz";
        sha512 = "eRzhrN1WSINYCDCbrz796z37LOe3m5tmW7RQf6oBntukAG1nmovJvhnwHHRMAfeoItc1m2Hk02WER2aQ/iqs+A==";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "range-parser-1.0.3" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.0.3.tgz";
        sha1 = "6872823535c692e2c2a0103826afd82c2e0ff175";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "raw-body-2.3.2" = {
      name = "raw-body";
      packageName = "raw-body";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/raw-body/-/raw-body-2.3.2.tgz";
        sha1 = "bcd60c77d3eb93cde0050295c3f379389bc88f89";
      };
    };
    "request-2.87.0" = {
      name = "request";
      packageName = "request";
      version = "2.87.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.87.0.tgz";
        sha512 = "fcogkm7Az5bsS6Sl0sibkbhcKsnyon/jV1kF3ajGmF0c8HrttdKTPRT9hieOaQHA5HEq6r8OyWOo/o781C1tNw==";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "safe-buffer-5.1.1" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.1.tgz";
        sha512 = "kKvNJn6Mm93gAczWVJg7wH+wGYWNrDHdWvpUmHyEsgCtIwwo3bqPtV4tR5tuPaUhTOo/kvhVwd8XwwOllGYkbg==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "send-0.13.0" = {
      name = "send";
      packageName = "send";
      version = "0.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.13.0.tgz";
        sha1 = "518f921aeb0560aec7dcab2990b14cf6f3cce5de";
      };
    };
    "send-0.13.2" = {
      name = "send";
      packageName = "send";
      version = "0.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.13.2.tgz";
        sha1 = "765e7607c8055452bba6f0b052595350986036de";
      };
    };
    "send-0.16.2" = {
      name = "send";
      packageName = "send";
      version = "0.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.16.2.tgz";
        sha512 = "E64YFPUssFHEFBvpbbjr44NCLtI1AohxQ8ZSiJjQLskAdKuriYEP6VyGEsRDH8ScozGpkaX1BGvhanqCwkcEZw==";
      };
    };
    "serve-static-1.10.3" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.10.3.tgz";
        sha1 = "ce5a6ecd3101fed5ec09827dac22a9c29bfb0535";
      };
    };
    "serve-static-1.13.2" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.13.2.tgz";
        sha512 = "p/tdJrO4U387R9oMjb1oj7qSMaMfmOyd4j9hOFoxZe2baQszgHcSWjuya/CiT5kgZZKRudHNOA0pYXOl8rQ5nw==";
      };
    };
    "setprototypeof-1.0.3" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.3.tgz";
        sha1 = "66567e37043eeb4f04d91bd658c0cbefb55b8e04";
      };
    };
    "setprototypeof-1.1.0" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.1.0.tgz";
        sha512 = "BvE/TwpZX4FXExxOxZyRGQQv651MSwmWKZGqvmPcRIjDqWub67kTKuIMx43cZZrS/cBBzwBcNDWoFxt2XEFIpQ==";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "sshpk-1.14.2" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.14.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.14.2.tgz";
        sha1 = "c6fc61648a3d9c4e764fd3fcdf4ea105e492ba98";
      };
    };
    "statuses-1.2.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.2.1.tgz";
        sha1 = "dded45cc18256d51ed40aec142489d5c61026d28";
      };
    };
    "statuses-1.4.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.4.0.tgz";
        sha512 = "zhSCtt8v2NDrRlPQpCNtw/heZLtfUDqxBM1udqikb/Hbk52LK4nQSwr10u77iopCW5LsyHpuXS0GnEc48mLeew==";
      };
    };
    "strftime-0.10.0" = {
      name = "strftime";
      packageName = "strftime";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strftime/-/strftime-0.10.0.tgz";
        sha1 = "b3f0fa419295202a5a289f6d6be9f4909a617193";
      };
    };
    "strip-eof-1.0.0" = {
      name = "strip-eof";
      packageName = "strip-eof";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz";
        sha1 = "bb43ff5598a6eb05d89b59fcd129c983313606bf";
      };
    };
    "testa-../testa" = {
      name = "testa";
      packageName = "testa";
      version = "0.0.1";
      src = ./testa;
    };
    "tough-cookie-2.3.4" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.4.tgz";
        sha512 = "TZ6TTfI5NtZnuyy/Kecv+CnoROnyXn2DN97LontgQpCwsX2XyLYCC0ENhYkehSOwAp8rTQKc/NUIF7BkQ5rKLA==";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "type-is-1.6.16" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.16.tgz";
        sha512 = "HRkVv/5qY2G6I8iab9cI7v1bOIdhm94dVjQCPFElW9W+3GeDOSHmy2EBYe4VTApuzolPcmgFTN3ftVJRKR2J9Q==";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "utils-merge-1.0.1" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.1.tgz";
        sha1 = "9f95710f50a267947b2ccc124741c1028427e713";
      };
    };
    "uuid-3.3.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.0.tgz";
        sha512 = "ijO9N2xY/YaOqQ5yz5c4sy2ZjWmA6AR6zASb/gdpeKZ8+948CxwfMW9RrKVk5may6ev8c0/Xguu32e2Llelpqw==";
      };
    };
    "vary-1.0.1" = {
      name = "vary";
      packageName = "vary";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.0.1.tgz";
        sha1 = "99e4981566a286118dfb2b817357df7993376d10";
      };
    };
    "vary-1.1.2" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.2.tgz";
        sha1 = "2299f02c6ded30d4a5961b0b9f74524a18f634fc";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "which-1.3.1" = {
      name = "which";
      packageName = "which";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.3.1.tgz";
        sha512 = "HxJdYWq1MTIQbJ3nw0cqssHoTNU267KlrDuGZ1WYlxDStUtKUhOaJmh112/TZmHxxUfuJqPXSOm7tDyas0OSIQ==";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "yallist-2.1.2" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.1.2.tgz";
        sha1 = "1c11f9218f076089a47dd512f93c6699a6a81d52";
      };
    };
  };
in
{
  async = nodeEnv.buildNodePackage {
    name = "async";
    packageName = "async";
    version = "2.6.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/async/-/async-2.6.1.tgz";
      sha512 = "fNEiL2+AZt6AlAw/29Cr0UDe4sRAHCpEHh54WMz+Bb7QfNcFw4h3loofyJpLeQs4Yx7yuqu/2dLgM5hKOs6HlQ==";
    };
    dependencies = [
      sources."lodash-4.17.10"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Higher-order functions and common patterns for asynchronous code";
      homepage = https://caolan.github.io/async/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "nijs-0.0.25" = nodeEnv.buildNodePackage {
    name = "nijs";
    packageName = "nijs";
    version = "0.0.25";
    src = fetchurl {
      url = "https://registry.npmjs.org/nijs/-/nijs-0.0.25.tgz";
      sha1 = "04b035cb530d46859d1018839a518c029133f676";
    };
    dependencies = [
      sources."optparse-1.0.5"
      sources."slasp-0.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An internal DSL for the Nix package manager in JavaScript";
      homepage = "https://github.com/svanderburg/nijs#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "commander-2.9.x" = nodeEnv.buildNodePackage {
    name = "commander";
    packageName = "commander";
    version = "2.9.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
      sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
    };
    dependencies = [
      sources."graceful-readlink-1.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "the complete solution for node.js command-line programs";
      homepage = "https://github.com/tj/commander.js#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  underscore = nodeEnv.buildNodePackage {
    name = "underscore";
    packageName = "underscore";
    version = "1.9.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/underscore/-/underscore-1.9.1.tgz";
      sha512 = "5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript's functional programming helper library.";
      homepage = http://underscorejs.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "semver-http://registry.npmjs.org/semver/-/semver-5.0.3.tgz" = nodeEnv.buildNodePackage {
    name = "semver";
    packageName = "semver";
    version = "5.0.3";
    src = fetchurl {
      name = "semver-5.0.3.tar.gz";
      url = http://registry.npmjs.org/semver/-/semver-5.0.3.tgz;
      sha256 = "131385bf0466cecc69e5bbf3c0a8f41174b8c832aa2e9b40f37cb4f4ad8c47f1";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The semantic version parser used by npm.";
      license = "ISC";
    };
    production = true;
    bypassCache = false;
  };
  "express-git+https://github.com/strongloop/express.git" = nodeEnv.buildNodePackage {
    name = "express";
    packageName = "express";
    version = "4.16.3";
    src = fetchgit {
      url = "https://github.com/strongloop/express.git";
      rev = "3ed5090ca91f6a387e66370d57ead94d886275e1";
      sha256 = "9be65f13387002357a68a0024d1fb8b27dc08850d42b96fd8e442c692ce73c14";
    };
    dependencies = [
      (sources."accepts-1.3.5" // {
        dependencies = [
          (sources."mime-types-2.1.18" // {
            dependencies = [
              sources."mime-db-1.33.0"
            ];
          })
          sources."negotiator-0.6.1"
        ];
      })
      sources."array-flatten-1.1.1"
      (sources."body-parser-1.18.2" // {
        dependencies = [
          sources."bytes-3.0.0"
          (sources."http-errors-1.6.3" // {
            dependencies = [
              sources."inherits-2.0.3"
            ];
          })
          sources."iconv-lite-0.4.19"
          (sources."raw-body-2.3.2" // {
            dependencies = [
              (sources."http-errors-1.6.2" // {
                dependencies = [
                  sources."depd-1.1.1"
                  sources."inherits-2.0.3"
                  sources."setprototypeof-1.0.3"
                ];
              })
              sources."unpipe-1.0.0"
            ];
          })
        ];
      })
      sources."content-disposition-0.5.2"
      sources."content-type-1.0.4"
      sources."cookie-0.3.1"
      sources."cookie-signature-1.0.6"
      (sources."debug-2.6.9" // {
        dependencies = [
          sources."ms-2.0.0"
        ];
      })
      sources."depd-1.1.2"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      (sources."finalhandler-1.1.1" // {
        dependencies = [
          sources."unpipe-1.0.0"
        ];
      })
      sources."fresh-0.5.2"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      (sources."on-finished-2.3.0" // {
        dependencies = [
          sources."ee-first-1.1.1"
        ];
      })
      sources."parseurl-1.3.2"
      sources."path-to-regexp-0.1.7"
      (sources."proxy-addr-2.0.3" // {
        dependencies = [
          sources."forwarded-0.1.2"
          sources."ipaddr.js-1.6.0"
        ];
      })
      sources."qs-6.5.1"
      sources."range-parser-1.2.0"
      sources."safe-buffer-5.1.1"
      (sources."send-0.16.2" // {
        dependencies = [
          sources."destroy-1.0.4"
          (sources."http-errors-1.6.3" // {
            dependencies = [
              sources."inherits-2.0.3"
            ];
          })
          sources."mime-1.4.1"
          sources."ms-2.0.0"
        ];
      })
      sources."serve-static-1.13.2"
      sources."setprototypeof-1.1.0"
      sources."statuses-1.4.0"
      (sources."type-is-1.6.16" // {
        dependencies = [
          sources."media-typer-0.3.0"
          (sources."mime-types-2.1.18" // {
            dependencies = [
              sources."mime-db-1.33.0"
            ];
          })
        ];
      })
      sources."utils-merge-1.0.1"
      sources."vary-1.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, unopinionated, minimalist web framework";
      homepage = http://expressjs.com/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "express-git+https://github.com/strongloop/express.git#ef7ad68" = nodeEnv.buildNodePackage {
    name = "express";
    packageName = "express";
    version = "4.13.3";
    src = fetchgit {
      url = "https://github.com/strongloop/express.git";
      rev = "ef7ad681b245fba023843ce94f6bcb8e275bbb8e";
      sha256 = "f65a66e4eb61ef4f43432cf597968a6a0072a853d53d15db619a663ed07c601f";
    };
    dependencies = [
      (sources."accepts-1.2.13" // {
        dependencies = [
          (sources."mime-types-2.1.18" // {
            dependencies = [
              sources."mime-db-1.33.0"
            ];
          })
          sources."negotiator-0.5.3"
        ];
      })
      sources."array-flatten-1.1.1"
      sources."content-disposition-0.5.0"
      sources."content-type-1.0.4"
      sources."cookie-0.1.3"
      sources."cookie-signature-1.0.6"
      (sources."debug-2.2.0" // {
        dependencies = [
          sources."ms-0.7.1"
        ];
      })
      sources."depd-1.0.1"
      sources."escape-html-1.0.2"
      sources."etag-1.7.0"
      (sources."finalhandler-0.4.0" // {
        dependencies = [
          sources."unpipe-1.0.0"
        ];
      })
      sources."fresh-0.3.0"
      sources."merge-descriptors-1.0.0"
      sources."methods-1.1.2"
      (sources."on-finished-2.3.0" // {
        dependencies = [
          sources."ee-first-1.1.1"
        ];
      })
      sources."parseurl-1.3.2"
      sources."path-to-regexp-0.1.7"
      (sources."proxy-addr-1.0.10" // {
        dependencies = [
          sources."forwarded-0.1.2"
          sources."ipaddr.js-1.0.5"
        ];
      })
      sources."qs-4.0.0"
      sources."range-parser-1.0.3"
      (sources."send-0.13.0" // {
        dependencies = [
          sources."destroy-1.0.3"
          (sources."http-errors-1.3.1" // {
            dependencies = [
              sources."inherits-2.0.3"
            ];
          })
          sources."mime-1.3.4"
          sources."ms-0.7.1"
          sources."statuses-1.2.1"
        ];
      })
      (sources."serve-static-1.10.3" // {
        dependencies = [
          sources."escape-html-1.0.3"
          (sources."send-0.13.2" // {
            dependencies = [
              sources."depd-1.1.2"
              sources."destroy-1.0.4"
              (sources."http-errors-1.3.1" // {
                dependencies = [
                  sources."inherits-2.0.3"
                ];
              })
              sources."mime-1.3.4"
              sources."ms-0.7.1"
              sources."statuses-1.2.1"
            ];
          })
        ];
      })
      (sources."type-is-1.6.16" // {
        dependencies = [
          sources."media-typer-0.3.0"
          (sources."mime-types-2.1.18" // {
            dependencies = [
              sources."mime-db-1.33.0"
            ];
          })
        ];
      })
      sources."utils-merge-1.0.0"
      sources."vary-1.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, unopinionated, minimalist web framework";
      homepage = http://expressjs.com/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "express-git+https://github.com/strongloop/express.git#master" = nodeEnv.buildNodePackage {
    name = "express";
    packageName = "express";
    version = "4.16.3";
    src = fetchgit {
      url = "https://github.com/strongloop/express.git";
      rev = "3ed5090ca91f6a387e66370d57ead94d886275e1";
      sha256 = "9be65f13387002357a68a0024d1fb8b27dc08850d42b96fd8e442c692ce73c14";
    };
    dependencies = [
      (sources."accepts-1.3.5" // {
        dependencies = [
          (sources."mime-types-2.1.18" // {
            dependencies = [
              sources."mime-db-1.33.0"
            ];
          })
          sources."negotiator-0.6.1"
        ];
      })
      sources."array-flatten-1.1.1"
      (sources."body-parser-1.18.2" // {
        dependencies = [
          sources."bytes-3.0.0"
          (sources."http-errors-1.6.3" // {
            dependencies = [
              sources."inherits-2.0.3"
            ];
          })
          sources."iconv-lite-0.4.19"
          (sources."raw-body-2.3.2" // {
            dependencies = [
              (sources."http-errors-1.6.2" // {
                dependencies = [
                  sources."depd-1.1.1"
                  sources."inherits-2.0.3"
                  sources."setprototypeof-1.0.3"
                ];
              })
              sources."unpipe-1.0.0"
            ];
          })
        ];
      })
      sources."content-disposition-0.5.2"
      sources."content-type-1.0.4"
      sources."cookie-0.3.1"
      sources."cookie-signature-1.0.6"
      (sources."debug-2.6.9" // {
        dependencies = [
          sources."ms-2.0.0"
        ];
      })
      sources."depd-1.1.2"
      sources."encodeurl-1.0.2"
      sources."escape-html-1.0.3"
      sources."etag-1.8.1"
      (sources."finalhandler-1.1.1" // {
        dependencies = [
          sources."unpipe-1.0.0"
        ];
      })
      sources."fresh-0.5.2"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      (sources."on-finished-2.3.0" // {
        dependencies = [
          sources."ee-first-1.1.1"
        ];
      })
      sources."parseurl-1.3.2"
      sources."path-to-regexp-0.1.7"
      (sources."proxy-addr-2.0.3" // {
        dependencies = [
          sources."forwarded-0.1.2"
          sources."ipaddr.js-1.6.0"
        ];
      })
      sources."qs-6.5.1"
      sources."range-parser-1.2.0"
      sources."safe-buffer-5.1.1"
      (sources."send-0.16.2" // {
        dependencies = [
          sources."destroy-1.0.4"
          (sources."http-errors-1.6.3" // {
            dependencies = [
              sources."inherits-2.0.3"
            ];
          })
          sources."mime-1.4.1"
          sources."ms-2.0.0"
        ];
      })
      sources."serve-static-1.13.2"
      sources."setprototypeof-1.1.0"
      sources."statuses-1.4.0"
      (sources."type-is-1.6.16" // {
        dependencies = [
          sources."media-typer-0.3.0"
          (sources."mime-types-2.1.18" // {
            dependencies = [
              sources."mime-db-1.33.0"
            ];
          })
        ];
      })
      sources."utils-merge-1.0.1"
      sources."vary-1.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, unopinionated, minimalist web framework";
      homepage = http://expressjs.com/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "nijs-svanderburg/nijs" = nodeEnv.buildNodePackage {
    name = "nijs";
    packageName = "nijs";
    version = "0.0.25";
    src = fetchgit {
      url = "git://github.com/svanderburg/nijs";
      rev = "4e2738cbff3a43aba9297315ca5120cecf8dae3e";
      sha256 = "544411ad03bbc67338dc9db90a237d33e2fb20c5778d358ae3f7fe1d1dd90880";
    };
    dependencies = [
      sources."optparse-1.0.5"
      sources."slasp-0.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An internal DSL for the Nix package manager in JavaScript";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "lodash-github:lodash/lodash" = nodeEnv.buildNodePackage {
    name = "lodash";
    packageName = "lodash";
    version = "4.17.4";
    src = fetchgit {
      url = "git://github.com/lodash/lodash";
      rev = "4ea8c2ec249be046a0f4ae32539d652194caf74f";
      sha256 = "65d5a3801a1d9d2a71f54452eae4bc9f45ab1b5efb38d4e584a6104ac69db9dc";
    };
    buildInputs = globalBuildInputs;
    meta = {
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "testb-./testb" = nodeEnv.buildNodePackage {
    name = "testb";
    packageName = "testb";
    version = "0.0.1";
    src = ./testb;
    dependencies = [
      sources."testa-../testa"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = false;
  };
  es5-ext = nodeEnv.buildNodePackage {
    name = "es5-ext";
    packageName = "es5-ext";
    version = "0.10.45";
    src = fetchurl {
      url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.45.tgz";
      sha512 = "FkfM6Vxxfmztilbxxz5UKSD4ICMf5tSpRFtDNtkAhOxZ0EKtX6qwmXNyH/sFyIbX2P/nU5AMiA9jilWsUGJzCQ==";
    };
    dependencies = [
      (sources."es6-iterator-2.0.3" // {
        dependencies = [
          sources."d-1.0.0"
          sources."es5-ext-0.10.45"
        ];
      })
      (sources."es6-symbol-3.1.1" // {
        dependencies = [
          sources."d-1.0.0"
          sources."es5-ext-0.10.45"
        ];
      })
      sources."next-tick-1.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "ECMAScript extensions and shims";
      homepage = "https://github.com/medikoo/es5-ext#readme";
      license = "ISC";
    };
    production = true;
    bypassCache = false;
  };
  grunt-cli = nodeEnv.buildNodePackage {
    name = "grunt-cli";
    packageName = "grunt-cli";
    version = "1.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz";
      sha1 = "562b119ebb069ddb464ace2845501be97b35b6a8";
    };
    dependencies = [
      (sources."findup-sync-0.3.0" // {
        dependencies = [
          (sources."glob-5.0.15" // {
            dependencies = [
              (sources."inflight-1.0.6" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."inherits-2.0.3"
              (sources."minimatch-3.0.4" // {
                dependencies = [
                  (sources."brace-expansion-1.1.11" // {
                    dependencies = [
                      sources."balanced-match-1.0.0"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."once-1.4.0" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."path-is-absolute-1.0.1"
            ];
          })
        ];
      })
      sources."grunt-known-options-1.1.0"
      (sources."nopt-3.0.6" // {
        dependencies = [
          sources."abbrev-1.1.1"
        ];
      })
      sources."resolve-1.1.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The grunt command line interface";
      homepage = "https://github.com/gruntjs/grunt-cli#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  bower = nodeEnv.buildNodePackage {
    name = "bower";
    packageName = "bower";
    version = "1.8.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/bower/-/bower-1.8.4.tgz";
      sha1 = "e7876a076deb8137f7d06525dc5e8c66db82f28a";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The browser package manager";
      homepage = http://bower.io/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  coffee-script = nodeEnv.buildNodePackage {
    name = "coffee-script";
    packageName = "coffee-script";
    version = "1.12.7";
    src = fetchurl {
      url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.12.7.tgz";
      sha512 = "fLeEhqwymYat/MpTPUjSKHVYYl0ec2mOyALEMLmzr5i1isuG+6jfI2j2d5oBO3VIzgUXgBVIcOT9uH1TFxBckw==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Unfancy JavaScript";
      homepage = http://coffeescript.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  floomatic = nodeEnv.buildNodePackage {
    name = "floomatic";
    packageName = "floomatic";
    version = "0.5.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/floomatic/-/floomatic-0.5.5.tgz";
      sha1 = "a2174dc25cc21ff584f1020f7790b45156a38003";
    };
    dependencies = [
      sources."async-1.5.2"
      sources."dmp-1.0.0"
      (sources."floorine-0.3.0" // {
        dependencies = [
          sources."strftime-0.10.0"
        ];
      })
      (sources."fsevents-1.2.4" // {
        dependencies = [
          sources."nan-2.10.0"
        ];
      })
      sources."lodash-4.17.10"
      (sources."minimatch-3.0.4" // {
        dependencies = [
          (sources."brace-expansion-1.1.11" // {
            dependencies = [
              sources."balanced-match-1.0.0"
              sources."concat-map-0.0.1"
            ];
          })
        ];
      })
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."native-diff-match-patch-0.3.1"
      sources."open-0.0.5"
      (sources."optimist-0.6.1" // {
        dependencies = [
          sources."minimist-0.0.10"
          sources."wordwrap-0.0.3"
        ];
      })
      (sources."request-2.87.0" // {
        dependencies = [
          sources."aws-sign2-0.7.0"
          sources."aws4-1.7.0"
          sources."caseless-0.12.0"
          (sources."combined-stream-1.0.6" // {
            dependencies = [
              sources."delayed-stream-1.0.0"
            ];
          })
          sources."extend-3.0.1"
          sources."forever-agent-0.6.1"
          (sources."form-data-2.3.2" // {
            dependencies = [
              sources."asynckit-0.4.0"
            ];
          })
          (sources."har-validator-5.0.3" // {
            dependencies = [
              (sources."ajv-5.5.2" // {
                dependencies = [
                  sources."co-4.6.0"
                  sources."fast-deep-equal-1.1.0"
                  sources."fast-json-stable-stringify-2.0.0"
                  sources."json-schema-traverse-0.3.1"
                ];
              })
              sources."har-schema-2.0.0"
            ];
          })
          (sources."http-signature-1.2.0" // {
            dependencies = [
              sources."assert-plus-1.0.0"
              (sources."jsprim-1.4.1" // {
                dependencies = [
                  sources."extsprintf-1.3.0"
                  sources."json-schema-0.2.3"
                  (sources."verror-1.10.0" // {
                    dependencies = [
                      sources."core-util-is-1.0.2"
                    ];
                  })
                ];
              })
              (sources."sshpk-1.14.2" // {
                dependencies = [
                  sources."asn1-0.2.3"
                  sources."bcrypt-pbkdf-1.0.1"
                  sources."dashdash-1.14.1"
                  sources."ecc-jsbn-0.1.1"
                  sources."getpass-0.1.7"
                  sources."jsbn-0.1.1"
                  sources."safer-buffer-2.1.2"
                  sources."tweetnacl-0.14.5"
                ];
              })
            ];
          })
          sources."is-typedarray-1.0.0"
          sources."isstream-0.1.2"
          sources."json-stringify-safe-5.0.1"
          (sources."mime-types-2.1.18" // {
            dependencies = [
              sources."mime-db-1.33.0"
            ];
          })
          sources."oauth-sign-0.8.2"
          sources."performance-now-2.1.0"
          sources."qs-6.5.2"
          sources."safe-buffer-5.1.2"
          (sources."tough-cookie-2.3.4" // {
            dependencies = [
              sources."punycode-1.4.1"
            ];
          })
          sources."tunnel-agent-0.6.0"
          sources."uuid-3.3.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A headless [Floobits](https://floobits.com/) workspace and disk watcher. Handy for shipping changes to a testing server.";
      homepage = https://github.com/Floobits/floomatic/;
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = false;
  };
  "@sindresorhus/df" = nodeEnv.buildNodePackage {
    name = "_at_sindresorhus_slash_df";
    packageName = "@sindresorhus/df";
    version = "2.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@sindresorhus/df/-/df-2.1.0.tgz";
      sha1 = "d208cf27e06f0bb476d14d7deccd7d726e9aa389";
    };
    dependencies = [
      (sources."execa-0.2.2" // {
        dependencies = [
          (sources."cross-spawn-async-2.2.5" // {
            dependencies = [
              (sources."lru-cache-4.1.3" // {
                dependencies = [
                  sources."pseudomap-1.0.2"
                  sources."yallist-2.1.2"
                ];
              })
              (sources."which-1.3.1" // {
                dependencies = [
                  sources."isexe-2.0.0"
                ];
              })
            ];
          })
          sources."npm-run-path-1.0.0"
          sources."object-assign-4.1.1"
          sources."path-key-1.0.0"
          sources."strip-eof-1.0.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Get free disk space info from `df -kP`";
      homepage = "https://github.com/sindresorhus/df#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  "esprima-fb-~3001.0001.0000-dev-harmony-fb" = nodeEnv.buildNodePackage {
    name = "esprima-fb";
    packageName = "esprima-fb";
    version = "3001.1.0-dev-harmony-fb";
    src = fetchurl {
      url = "https://registry.npmjs.org/esprima-fb/-/esprima-fb-3001.0001.0000-dev-harmony-fb.tgz";
      sha1 = "b77d37abcd38ea0b77426bb8bc2922ce6b426411";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Facebook-specific fork of the esprima project";
      homepage = https://github.com/facebook/esprima/tree/fb-harmony;
    };
    production = true;
    bypassCache = false;
  };
  "bcrypt-0.8.x" = nodeEnv.buildNodePackage {
    name = "bcrypt";
    packageName = "bcrypt";
    version = "0.8.7";
    src = fetchurl {
      url = "https://registry.npmjs.org/bcrypt/-/bcrypt-0.8.7.tgz";
      sha1 = "bc3875a9afd0a7b2cd231a6a7f218a5ce156b093";
    };
    dependencies = [
      sources."bindings-1.2.1"
      sources."nan-2.3.5"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A bcrypt library for NodeJS.";
      homepage = "https://github.com/ncb000gt/node.bcrypt.js#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = false;
  };
  hiredis = nodeEnv.buildNodePackage {
    name = "hiredis";
    packageName = "hiredis";
    version = "0.5.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/hiredis/-/hiredis-0.5.0.tgz";
      sha1 = "db03a98becd7003d13c260043aceecfacdf59b87";
    };
    dependencies = [
      sources."bindings-1.3.0"
      sources."nan-2.10.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Wrapper for reply processing code in hiredis";
      homepage = http://github.com/redis/hiredis-node;
      license = "BSD-3-Clause";
    };
    production = true;
    bypassCache = false;
  };
}