# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "lodash-4.15.0" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.15.0.tgz";
        sha1 = "3162391d8f0140aa22cf8f6b3c34d6b7f63d3aa9";
      };
    };
    "optparse-1.0.5" = {
      name = "optparse";
      packageName = "optparse";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/optparse/-/optparse-1.0.5.tgz";
        sha1 = "75e75a96506611eb1c65ba89018ff08a981e2c16";
      };
    };
    "slasp-0.0.4" = {
      name = "slasp";
      packageName = "slasp";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/slasp/-/slasp-0.0.4.tgz";
        sha1 = "9adc26ee729a0f95095851a5489f87a5258d57a9";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "accepts-1.3.3" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz";
        sha1 = "c3ca7434938648c3e0d9c1e328dd68b622c284ca";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "content-disposition-0.5.1" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.1.tgz";
        sha1 = "87476c6a67c8daa87e32e87616df883ba7fb071b";
      };
    };
    "content-type-1.0.2" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.2.tgz";
        sha1 = "b7d113aee7a8dd27bd21133c4dc2529df1721eed";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "depd-1.1.0" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.0.tgz";
        sha1 = "e1bd82c6aab6ced965b97b88b17ed3e528ca18c3";
      };
    };
    "encodeurl-1.0.1" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.1.tgz";
        sha1 = "79e3d58655346909fe6f0f45a5de68103b294d20";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.7.0" = {
      name = "etag";
      packageName = "etag";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.7.0.tgz";
        sha1 = "03d30b5f67dd6e632d2945d30d6652731a34d5d8";
      };
    };
    "finalhandler-0.5.0" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.5.0.tgz";
        sha1 = "e9508abece9b6dba871a6942a1d7911b91911ac7";
      };
    };
    "fresh-0.3.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.3.0.tgz";
        sha1 = "651f838e22424e7566de161d8358caa199f83d4f";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "parseurl-1.3.1" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz";
        sha1 = "c8ab8c9223ba34888aa64a297b28853bec18da56";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "proxy-addr-1.1.2" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.1.2.tgz";
        sha1 = "b4cc5f22610d9535824c123aef9d3cf73c40ba37";
      };
    };
    "qs-6.2.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.0.tgz";
        sha1 = "3b7848c03c2dece69a9522b0fae8c4126d745f3b";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "send-0.14.1" = {
      name = "send";
      packageName = "send";
      version = "0.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.14.1.tgz";
        sha1 = "a954984325392f51532a7760760e459598c89f7a";
      };
    };
    "serve-static-1.11.1" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.11.1.tgz";
        sha1 = "d6cce7693505f733c759de57befc1af76c0f0805";
      };
    };
    "type-is-1.6.13" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.13.tgz";
        sha1 = "6e83ba7bc30cd33a7bb0b7fb00737a2085bf9d08";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "vary-1.1.0" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.0.tgz";
        sha1 = "e1e5affbbd16ae768dd2674394b9ad3022653140";
      };
    };
    "mime-types-2.1.11" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.11.tgz";
        sha1 = "c259c471bda808a85d6cd193b430a5fae4473b3c";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "mime-db-1.23.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.23.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.23.0.tgz";
        sha1 = "a31b4070adaea27d732ea333740a64d0ec9a6659";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "statuses-1.3.0" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.3.0.tgz";
        sha1 = "8e55758cb20e7682c1f4fce8dcab30bf01d1e07a";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "forwarded-0.1.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz";
        sha1 = "19ef9874c4ae1c297bcf078fde63a09b66a84363";
      };
    };
    "ipaddr.js-1.1.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.1.1.tgz";
        sha1 = "c791d95f52b29c1247d5df80ada39b8a73647230";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "http-errors-1.5.0" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.5.0.tgz";
        sha1 = "b1cb3d8260fd8e2386cad3189045943372d48211";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "inherits-2.0.1" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz";
        sha1 = "b17d08d326b4423e568eff719f91b0b1cbdf69f1";
      };
    };
    "setprototypeof-1.0.1" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.1.tgz";
        sha1 = "52009b27888c4dc48f591949c0a8275834c1ca7e";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
    "accepts-1.2.13" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.2.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.2.13.tgz";
        sha1 = "e5f1f3928c6d95fd96558c36ec3d9d0de4a6ecea";
      };
    };
    "content-disposition-0.5.0" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.0.tgz";
        sha1 = "4284fe6ae0630874639e44e80a418c2934135e9e";
      };
    };
    "cookie-0.1.3" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.1.3.tgz";
        sha1 = "e734a5c1417fce472d5aef82c381cabb64d1a435";
      };
    };
    "depd-1.0.1" = {
      name = "depd";
      packageName = "depd";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.0.1.tgz";
        sha1 = "80aec64c9d6d97e65cc2a9caa93c0aa6abf73aaa";
      };
    };
    "escape-html-1.0.2" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.2.tgz";
        sha1 = "d77d32fa98e38c2f41ae85e9278e0e0e6ba1022c";
      };
    };
    "finalhandler-0.4.0" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.4.0.tgz";
        sha1 = "965a52d9e8d05d2b857548541fb89b53a2497d9b";
      };
    };
    "merge-descriptors-1.0.0" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.0.tgz";
        sha1 = "2169cf7538e1b0cc87fb88e1502d8474bbf79864";
      };
    };
    "proxy-addr-1.0.10" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.0.10.tgz";
        sha1 = "0d40a82f801fc355567d2ecb65efe3f077f121c5";
      };
    };
    "qs-4.0.0" = {
      name = "qs";
      packageName = "qs";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-4.0.0.tgz";
        sha1 = "c31d9b74ec27df75e543a86c78728ed8d4623607";
      };
    };
    "range-parser-1.0.3" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.0.3.tgz";
        sha1 = "6872823535c692e2c2a0103826afd82c2e0ff175";
      };
    };
    "send-0.13.0" = {
      name = "send";
      packageName = "send";
      version = "0.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.13.0.tgz";
        sha1 = "518f921aeb0560aec7dcab2990b14cf6f3cce5de";
      };
    };
    "serve-static-1.10.3" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.10.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.10.3.tgz";
        sha1 = "ce5a6ecd3101fed5ec09827dac22a9c29bfb0535";
      };
    };
    "vary-1.0.1" = {
      name = "vary";
      packageName = "vary";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.0.1.tgz";
        sha1 = "99e4981566a286118dfb2b817357df7993376d10";
      };
    };
    "negotiator-0.5.3" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.5.3.tgz";
        sha1 = "269d5c476810ec92edbe7b6c2f28316384f9a7e8";
      };
    };
    "ipaddr.js-1.0.5" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.0.5.tgz";
        sha1 = "5fa78cf301b825c78abc3042d812723049ea23c7";
      };
    };
    "destroy-1.0.3" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.3.tgz";
        sha1 = "b433b4724e71fd8551d9885174851c5fc377e2c9";
      };
    };
    "http-errors-1.3.1" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.3.1.tgz";
        sha1 = "197e22cdebd4198585e8694ef6786197b91ed942";
      };
    };
    "statuses-1.2.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.2.1.tgz";
        sha1 = "dded45cc18256d51ed40aec142489d5c61026d28";
      };
    };
    "send-0.13.2" = {
      name = "send";
      packageName = "send";
      version = "0.13.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.13.2.tgz";
        sha1 = "765e7607c8055452bba6f0b052595350986036de";
      };
    };
    "testa-../testa" = {
      name = "testa";
      packageName = "testa";
      version = "0.0.1";
      src = ./testa;
    };
    "es6-iterator-2.0.0" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.0.tgz";
        sha1 = "bd968567d61635e33c0b80727613c9cb4b096bac";
      };
    };
    "es6-symbol-3.1.0" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.0.tgz";
        sha1 = "94481c655e7a7cad82eba832d97d5433496d7ffa";
      };
    };
    "d-0.1.1" = {
      name = "d";
      packageName = "d";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-0.1.1.tgz";
        sha1 = "da184c535d18d8ee7ba2aa229b914009fae11309";
      };
    };
    "es5-ext-0.10.12" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.12.tgz";
        sha1 = "aa84641d4db76b62abba5e45fd805ecbab140047";
      };
    };
    "findup-sync-0.3.0" = {
      name = "findup-sync";
      packageName = "findup-sync";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/findup-sync/-/findup-sync-0.3.0.tgz";
        sha1 = "37930aa5d816b777c03445e1966cc6790a4c0b16";
      };
    };
    "grunt-known-options-1.1.0" = {
      name = "grunt-known-options";
      packageName = "grunt-known-options";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/grunt-known-options/-/grunt-known-options-1.1.0.tgz";
        sha1 = "a4274eeb32fa765da5a7a3b1712617ce3b144149";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "resolve-1.1.7" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.1.7.tgz";
        sha1 = "203114d82ad2c5ed9e8e0411b3932875e889e97b";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha1 = "1bc936b9e02f4a603fcc222ecf7633d30b8b93b1";
      };
    };
    "inflight-1.0.5" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.5.tgz";
        sha1 = "db3204cd5a9de2e6cd890b85c6e2f66bcf4f620a";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "path-is-absolute-1.0.0" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.0.tgz";
        sha1 = "263dada66ab3f2fb10bf7f9d24dd8f3e570ef912";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.6" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.6.tgz";
        sha1 = "7197d7eaa9b87e648390ea61fc66c84427420df9";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "abbrev-1.0.9" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.0.9.tgz";
        sha1 = "91b4792588a7738c25f35dd6f63752a2f8776135";
      };
    };
    "async-1.5.2" = {
      name = "async";
      packageName = "async";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.5.2.tgz";
        sha1 = "ec6a61ae56480c0c3cb241c95618e20892f9672a";
      };
    };
    "dmp-0.2.0" = {
      name = "dmp";
      packageName = "dmp";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dmp/-/dmp-0.2.0.tgz";
        sha1 = "71faa0efb8414e14683dd2e64466361487574876";
      };
    };
    "floorine-0.3.0" = {
      name = "floorine";
      packageName = "floorine";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/floorine/-/floorine-0.3.0.tgz";
        sha1 = "cfc23a889d629a22db04ba4b8ce357012d0f1e70";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "open-0.0.5" = {
      name = "open";
      packageName = "open";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/open/-/open-0.0.5.tgz";
        sha1 = "42c3e18ec95466b6bf0dc42f3a2945c3f0cad8fc";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "request-2.74.0" = {
      name = "request";
      packageName = "request";
      version = "2.74.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.74.0.tgz";
        sha1 = "7693ca768bbb0ea5c8ce08c084a45efa05b892ab";
      };
    };
    "fsevents-1.0.14" = {
      name = "fsevents";
      packageName = "fsevents";
      version = "1.0.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/fsevents/-/fsevents-1.0.14.tgz";
        sha1 = "558e8cc38643d8ef40fe45158486d0d25758eee4";
      };
    };
    "native-diff-match-patch-0.3.1" = {
      name = "native-diff-match-patch";
      packageName = "native-diff-match-patch";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/native-diff-match-patch/-/native-diff-match-patch-0.3.1.tgz";
        sha1 = "620304151a78171386ed2e2f3db2e7dfd6436707";
      };
    };
    "strftime-0.9.2" = {
      name = "strftime";
      packageName = "strftime";
      version = "0.9.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/strftime/-/strftime-0.9.2.tgz";
        sha1 = "bcca2861f29456d372aaf6a17811c8bc6f39f583";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.4.1" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.4.1.tgz";
        sha1 = "fde7d5292466d230e5ee0f4e038d9dfaab08fc61";
      };
    };
    "bl-1.1.2" = {
      name = "bl";
      packageName = "bl";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.1.2.tgz";
        sha1 = "fdca871a99713aa00d19e3bbba41c44787a65398";
      };
    };
    "caseless-0.11.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz";
        sha1 = "715b96ea9841593cc33067923f5ec60ebda4f7d7";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.0" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.0.tgz";
        sha1 = "5a474353b9f3353ddd8176dfd37b91c83a46f1d4";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-1.0.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-1.0.1.tgz";
        sha1 = "ae315db9a4907fa065502304a66d7733475ee37c";
      };
    };
    "har-validator-2.0.6" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz";
        sha1 = "cdcbc08188265ad119b6a5a7c8ab70eecfb5d27d";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "node-uuid-1.4.7" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz";
        sha1 = "6da5a17668c4b3dd59623bda11cf7fa4c1f60a6f";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "qs-6.2.1" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.1.tgz";
        sha1 = "ce03c5ff0935bc1d9d69a9f14cbd18e568d67625";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.1" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.1.tgz";
        sha1 = "99c77dfbb7d804249e8a299d4cb0fd81fef083fd";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "async-2.0.1" = {
      name = "async";
      packageName = "async";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.0.1.tgz";
        sha1 = "b709cc0280a9c36f09f4536be823c838a9049e25";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "commander-2.9.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
        sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
      };
    };
    "is-my-json-valid-2.13.1" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.13.1.tgz";
        sha1 = "d55778a82feb6b0963ff4be111d5d1684e890707";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz";
        sha1 = "c5061b6e0ef8a81775e50f5d66151bf6bf371107";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-2.0.0" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-2.0.0.tgz";
        sha1 = "3af1dd20fe85463910d469a385e33017d2a030d9";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.3.0" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.3.0.tgz";
        sha1 = "ce2e1bef835204b4f3099928c602f8b6ae615650";
      };
    };
    "sshpk-1.10.0" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.10.0.tgz";
        sha1 = "104d6ba2afb2ac099ab9567c0d193977f29c6dfa";
      };
    };
    "extsprintf-1.0.2" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz";
        sha1 = "e1080e0658e300b06294990cc70e1502235fd550";
      };
    };
    "json-schema-0.2.2" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.2.tgz";
        sha1 = "50354f19f603917c695f70b85afa77c3b0f23506";
      };
    };
    "verror-1.3.6" = {
      name = "verror";
      packageName = "verror";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.3.6.tgz";
        sha1 = "cff5df12946d297d2baaefaa2689e25be01c005c";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "dashdash-1.14.0" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.0.tgz";
        sha1 = "29e486c5418bf0f356034a993d51686a33e84141";
      };
    };
    "getpass-0.1.6" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.6.tgz";
        sha1 = "283ffd9fc1256840875311c1b60e8c40187110e6";
      };
    };
    "jsbn-0.1.0" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.0.tgz";
        sha1 = "650987da0dd74f4ebf5a11377a2aa2d273e97dfd";
      };
    };
    "tweetnacl-0.13.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.13.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.13.3.tgz";
        sha1 = "d628b56f3bcc3d5ae74ba9d4c1a704def5ab4b56";
      };
    };
    "jodid25519-1.0.2" = {
      name = "jodid25519";
      packageName = "jodid25519";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz";
        sha1 = "06d4912255093419477d425633606e0e90782967";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.0" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.0.tgz";
        sha1 = "3ca76b85241c7170bf7d9703e7b9aa74630040d4";
      };
    };
    "tweetnacl-0.14.3" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.3.tgz";
        sha1 = "3da382f670f25ded78d7b3d1792119bca0b7132d";
      };
    };
    "nan-2.4.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.4.0.tgz";
        sha1 = "fb3c59d45fe4effe215f0b890f8adf6eb32d2232";
      };
    };
    "node-pre-gyp-0.6.30" = {
      name = "node-pre-gyp";
      packageName = "node-pre-gyp";
      version = "0.6.30";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-pre-gyp/-/node-pre-gyp-0.6.30.tgz";
        sha1 = "64d3073a6f573003717ccfe30c89023297babba1";
      };
    };
    "npmlog-4.0.0" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-4.0.0.tgz";
        sha1 = "e094503961c70c1774eb76692080e8d578a9f88f";
      };
    };
    "rc-1.1.6" = {
      name = "rc";
      packageName = "rc";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/rc/-/rc-1.1.6.tgz";
        sha1 = "43651b76b6ae53b5c802f1151fa3fc3b059969c9";
      };
    };
    "rimraf-2.5.4" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz";
        sha1 = "96800093cbf1a0c86bd95b4625467535c29dfa04";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "tar-2.2.1" = {
      name = "tar";
      packageName = "tar";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-2.2.1.tgz";
        sha1 = "8e4d2a256c0e2185c6b18ad694aec968b83cb1d1";
      };
    };
    "tar-pack-3.1.4" = {
      name = "tar-pack";
      packageName = "tar-pack";
      version = "3.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar-pack/-/tar-pack-3.1.4.tgz";
        sha1 = "bc8cf9a22f5832739f12f3910dac1eb97b49708c";
      };
    };
    "are-we-there-yet-1.1.2" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.2.tgz";
        sha1 = "80e470e95a084794fe1899262c5667c6e88de1b3";
      };
    };
    "console-control-strings-1.1.0" = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "3d7cf4464db6446ea644bf4b39507f9851008e8e";
      };
    };
    "gauge-2.6.0" = {
      name = "gauge";
      packageName = "gauge";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-2.6.0.tgz";
        sha1 = "d35301ad18e96902b4751dcbbe40f4218b942a46";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "readable-stream-2.1.5" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.1.5.tgz";
        sha1 = "66fa8b720e1438b364681f2ad1a63c618448c9d0";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "aproba-1.0.4" = {
      name = "aproba";
      packageName = "aproba";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/aproba/-/aproba-1.0.4.tgz";
        sha1 = "2713680775e7614c8ba186c065d4e2e52d1072c0";
      };
    };
    "has-color-0.1.7" = {
      name = "has-color";
      packageName = "has-color";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-color/-/has-color-0.1.7.tgz";
        sha1 = "67144a5260c34fc3cca677d041daf52fe7b78b2f";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "signal-exit-3.0.0" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.0.tgz";
        sha1 = "3c0543b65d7b4fbc60b6cd94593d9bf436739be8";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "wide-align-1.1.0" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.0.tgz";
        sha1 = "40edde802a71fea1f070da3e62dcda2e7add96ad";
      };
    };
    "code-point-at-1.0.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.0.0.tgz";
        sha1 = "f69b192d3f7d91e382e4b71bddb77878619ab0c6";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "number-is-nan-1.0.0" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.0.tgz";
        sha1 = "c020f529c5282adfdd233d91d4b181c3d686dc4b";
      };
    };
    "deep-extend-0.4.1" = {
      name = "deep-extend";
      packageName = "deep-extend";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-extend/-/deep-extend-0.4.1.tgz";
        sha1 = "efe4113d08085f4e6f9687759810f807469e2253";
      };
    };
    "ini-1.3.4" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.4.tgz";
        sha1 = "0537cb79daf59b59a1a517dff706c86ec039162e";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "strip-json-comments-1.0.4" = {
      name = "strip-json-comments";
      packageName = "strip-json-comments";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-json-comments/-/strip-json-comments-1.0.4.tgz";
        sha1 = "1e15fbcac97d3ee99bf2d73b4c656b082bbafb91";
      };
    };
    "glob-7.0.6" = {
      name = "glob";
      packageName = "glob";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.0.6.tgz";
        sha1 = "211bafaf49e525b8cd93260d14ab136152b3f57a";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "block-stream-0.0.9" = {
      name = "block-stream";
      packageName = "block-stream";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/block-stream/-/block-stream-0.0.9.tgz";
        sha1 = "13ebfe778a03205cfe03751481ebb4b3300c126a";
      };
    };
    "fstream-1.0.10" = {
      name = "fstream";
      packageName = "fstream";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream/-/fstream-1.0.10.tgz";
        sha1 = "604e8a92fe26ffd9f6fae30399d4984e1ab22822";
      };
    };
    "graceful-fs-4.1.6" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.6.tgz";
        sha1 = "514c38772b31bee2e08bedc21a0aeb3abf54c19e";
      };
    };
    "fstream-ignore-1.0.5" = {
      name = "fstream-ignore";
      packageName = "fstream-ignore";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream-ignore/-/fstream-ignore-1.0.5.tgz";
        sha1 = "9c31dae34767018fe1d249b24dada67d092da105";
      };
    };
    "uid-number-0.0.6" = {
      name = "uid-number";
      packageName = "uid-number";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-number/-/uid-number-0.0.6.tgz";
        sha1 = "0ea10e8035e8eb5b8e4449f06da1c730663baa81";
      };
    };
    "execa-0.2.2" = {
      name = "execa";
      packageName = "execa";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/execa/-/execa-0.2.2.tgz";
        sha1 = "e2ead472c2c31aad6f73f1ac956eef45e12320cb";
      };
    };
    "cross-spawn-async-2.2.4" = {
      name = "cross-spawn-async";
      packageName = "cross-spawn-async";
      version = "2.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/cross-spawn-async/-/cross-spawn-async-2.2.4.tgz";
        sha1 = "c9a8d8e9a06502c7a46296e33a1a054b5d2f1812";
      };
    };
    "npm-run-path-1.0.0" = {
      name = "npm-run-path";
      packageName = "npm-run-path";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-run-path/-/npm-run-path-1.0.0.tgz";
        sha1 = "f5c32bf595fe81ae927daec52e82f8b000ac3c8f";
      };
    };
    "path-key-1.0.0" = {
      name = "path-key";
      packageName = "path-key";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-key/-/path-key-1.0.0.tgz";
        sha1 = "5d53d578019646c0d68800db4e146e6bdc2ac7af";
      };
    };
    "strip-eof-1.0.0" = {
      name = "strip-eof";
      packageName = "strip-eof";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-eof/-/strip-eof-1.0.0.tgz";
        sha1 = "bb43ff5598a6eb05d89b59fcd129c983313606bf";
      };
    };
    "lru-cache-4.0.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-4.0.1.tgz";
        sha1 = "1343955edaf2e37d9b9e7ee7241e27c4b9fb72be";
      };
    };
    "which-1.2.10" = {
      name = "which";
      packageName = "which";
      version = "1.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.2.10.tgz";
        sha1 = "91cd9bd0751322411b659b40f054b21de957ab2d";
      };
    };
    "pseudomap-1.0.2" = {
      name = "pseudomap";
      packageName = "pseudomap";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pseudomap/-/pseudomap-1.0.2.tgz";
        sha1 = "f052a28da70e618917ef0a8ac34c1ae5a68286b3";
      };
    };
    "yallist-2.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-2.0.0.tgz";
        sha1 = "306c543835f09ee1a4cb23b7bce9ab341c91cdd4";
      };
    };
    "isexe-1.1.2" = {
      name = "isexe";
      packageName = "isexe";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-1.1.2.tgz";
        sha1 = "36f3e22e60750920f5e7241a476a8c6a42275ad0";
      };
    };
  };
in
{
  async = nodeEnv.buildNodePackage {
    name = "async";
    packageName = "async";
    version = "2.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/async/-/async-2.0.1.tgz";
      sha1 = "b709cc0280a9c36f09f4536be823c838a9049e25";
    };
    dependencies = [
      sources."lodash-4.15.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Higher-order functions and common patterns for asynchronous code";
      homepage = "https://github.com/caolan/async#readme";
      license = "MIT";
    };
    production = true;
  };
  "nijs-0.0.23" = nodeEnv.buildNodePackage {
    name = "nijs";
    packageName = "nijs";
    version = "0.0.23";
    src = fetchurl {
      url = "https://registry.npmjs.org/nijs/-/nijs-0.0.23.tgz";
      sha1 = "dbf8f4a0acafbe3b8d9b71c24cbd1d851de6c31a";
    };
    dependencies = [
      sources."optparse-1.0.5"
      sources."slasp-0.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An internal DSL for the Nix package manager in JavaScript";
      homepage = https://github.com/svanderburg/nijs;
      license = "MIT";
    };
    production = true;
  };
  "commander-2.9.x" = nodeEnv.buildNodePackage {
    name = "commander";
    packageName = "commander";
    version = "2.9.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
      sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
    };
    dependencies = [
      sources."graceful-readlink-1.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "the complete solution for node.js command-line programs";
      homepage = "https://github.com/tj/commander.js#readme";
      license = "MIT";
    };
    production = true;
  };
  underscore = nodeEnv.buildNodePackage {
    name = "underscore";
    packageName = "underscore";
    version = "1.8.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/underscore/-/underscore-1.8.3.tgz";
      sha1 = "4f3fb53b106e6097fcf9cb4109f2a5e9bdfa5022";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "JavaScript's functional programming helper library.";
      homepage = http://underscorejs.org/;
      license = "MIT";
    };
    production = true;
  };
  "semver-http://registry.npmjs.org/semver/-/semver-5.0.3.tgz" = nodeEnv.buildNodePackage {
    name = "semver";
    packageName = "semver";
    version = "5.0.3";
    src = fetchurl {
      name = "semver-5.0.3.tar.gz";
      url = http://registry.npmjs.org/semver/-/semver-5.0.3.tgz;
      sha256 = "131385bf0466cecc69e5bbf3c0a8f41174b8c832aa2e9b40f37cb4f4ad8c47f1";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The semantic version parser used by npm.";
      license = "ISC";
    };
    production = true;
  };
  "express-git+https://github.com/strongloop/express.git" = nodeEnv.buildNodePackage {
    name = "express";
    packageName = "express";
    version = "4.14.0";
    src = fetchgit {
      url = "https://github.com/strongloop/express.git";
      rev = "3c54220a3495a7a2cdf580c3289ee37e835c0190";
      sha256 = "a855a1d20ec9e9c51374b807ac3106235e34241afbbdea3f670afc35dd8e3648";
    };
    dependencies = [
      (sources."accepts-1.3.3" // {
        dependencies = [
          (sources."mime-types-2.1.11" // {
            dependencies = [
              sources."mime-db-1.23.0"
            ];
          })
          sources."negotiator-0.6.1"
        ];
      })
      sources."array-flatten-1.1.1"
      sources."content-disposition-0.5.1"
      sources."content-type-1.0.2"
      sources."cookie-0.3.1"
      sources."cookie-signature-1.0.6"
      (sources."debug-2.2.0" // {
        dependencies = [
          sources."ms-0.7.1"
        ];
      })
      sources."depd-1.1.0"
      sources."encodeurl-1.0.1"
      sources."escape-html-1.0.3"
      sources."etag-1.7.0"
      (sources."finalhandler-0.5.0" // {
        dependencies = [
          sources."statuses-1.3.0"
          sources."unpipe-1.0.0"
        ];
      })
      sources."fresh-0.3.0"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      (sources."on-finished-2.3.0" // {
        dependencies = [
          sources."ee-first-1.1.1"
        ];
      })
      sources."parseurl-1.3.1"
      sources."path-to-regexp-0.1.7"
      (sources."proxy-addr-1.1.2" // {
        dependencies = [
          sources."forwarded-0.1.0"
          sources."ipaddr.js-1.1.1"
        ];
      })
      sources."qs-6.2.0"
      sources."range-parser-1.2.0"
      (sources."send-0.14.1" // {
        dependencies = [
          sources."destroy-1.0.4"
          (sources."http-errors-1.5.0" // {
            dependencies = [
              sources."inherits-2.0.1"
              sources."setprototypeof-1.0.1"
            ];
          })
          sources."mime-1.3.4"
          sources."ms-0.7.1"
          sources."statuses-1.3.0"
        ];
      })
      sources."serve-static-1.11.1"
      (sources."type-is-1.6.13" // {
        dependencies = [
          sources."media-typer-0.3.0"
          (sources."mime-types-2.1.11" // {
            dependencies = [
              sources."mime-db-1.23.0"
            ];
          })
        ];
      })
      sources."utils-merge-1.0.0"
      sources."vary-1.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, unopinionated, minimalist web framework";
      homepage = http://expressjs.com/;
      license = "MIT";
    };
    production = true;
  };
  "express-git+https://github.com/strongloop/express.git#ef7ad68" = nodeEnv.buildNodePackage {
    name = "express";
    packageName = "express";
    version = "4.13.3";
    src = fetchgit {
      url = "https://github.com/strongloop/express.git";
      rev = "ef7ad681b245fba023843ce94f6bcb8e275bbb8e";
      sha256 = "f65a66e4eb61ef4f43432cf597968a6a0072a853d53d15db619a663ed07c601f";
    };
    dependencies = [
      (sources."accepts-1.2.13" // {
        dependencies = [
          (sources."mime-types-2.1.11" // {
            dependencies = [
              sources."mime-db-1.23.0"
            ];
          })
          sources."negotiator-0.5.3"
        ];
      })
      sources."array-flatten-1.1.1"
      sources."content-disposition-0.5.0"
      sources."content-type-1.0.2"
      sources."cookie-0.1.3"
      sources."cookie-signature-1.0.6"
      (sources."debug-2.2.0" // {
        dependencies = [
          sources."ms-0.7.1"
        ];
      })
      sources."depd-1.0.1"
      sources."escape-html-1.0.2"
      sources."etag-1.7.0"
      (sources."finalhandler-0.4.0" // {
        dependencies = [
          sources."unpipe-1.0.0"
        ];
      })
      sources."fresh-0.3.0"
      sources."merge-descriptors-1.0.0"
      sources."methods-1.1.2"
      (sources."on-finished-2.3.0" // {
        dependencies = [
          sources."ee-first-1.1.1"
        ];
      })
      sources."parseurl-1.3.1"
      sources."path-to-regexp-0.1.7"
      (sources."proxy-addr-1.0.10" // {
        dependencies = [
          sources."forwarded-0.1.0"
          sources."ipaddr.js-1.0.5"
        ];
      })
      sources."qs-4.0.0"
      sources."range-parser-1.0.3"
      (sources."send-0.13.0" // {
        dependencies = [
          sources."destroy-1.0.3"
          (sources."http-errors-1.3.1" // {
            dependencies = [
              sources."inherits-2.0.1"
            ];
          })
          sources."mime-1.3.4"
          sources."ms-0.7.1"
          sources."statuses-1.2.1"
        ];
      })
      (sources."serve-static-1.10.3" // {
        dependencies = [
          sources."escape-html-1.0.3"
          (sources."send-0.13.2" // {
            dependencies = [
              sources."depd-1.1.0"
              sources."destroy-1.0.4"
              (sources."http-errors-1.3.1" // {
                dependencies = [
                  sources."inherits-2.0.1"
                ];
              })
              sources."mime-1.3.4"
              sources."ms-0.7.1"
              sources."statuses-1.2.1"
            ];
          })
        ];
      })
      (sources."type-is-1.6.13" // {
        dependencies = [
          sources."media-typer-0.3.0"
          (sources."mime-types-2.1.11" // {
            dependencies = [
              sources."mime-db-1.23.0"
            ];
          })
        ];
      })
      sources."utils-merge-1.0.0"
      sources."vary-1.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, unopinionated, minimalist web framework";
      homepage = http://expressjs.com/;
      license = "MIT";
    };
    production = true;
  };
  "express-git+https://github.com/strongloop/express.git#master" = nodeEnv.buildNodePackage {
    name = "express";
    packageName = "express";
    version = "4.14.0";
    src = fetchgit {
      url = "https://github.com/strongloop/express.git";
      rev = "3c54220a3495a7a2cdf580c3289ee37e835c0190";
      sha256 = "a855a1d20ec9e9c51374b807ac3106235e34241afbbdea3f670afc35dd8e3648";
    };
    dependencies = [
      (sources."accepts-1.3.3" // {
        dependencies = [
          (sources."mime-types-2.1.11" // {
            dependencies = [
              sources."mime-db-1.23.0"
            ];
          })
          sources."negotiator-0.6.1"
        ];
      })
      sources."array-flatten-1.1.1"
      sources."content-disposition-0.5.1"
      sources."content-type-1.0.2"
      sources."cookie-0.3.1"
      sources."cookie-signature-1.0.6"
      (sources."debug-2.2.0" // {
        dependencies = [
          sources."ms-0.7.1"
        ];
      })
      sources."depd-1.1.0"
      sources."encodeurl-1.0.1"
      sources."escape-html-1.0.3"
      sources."etag-1.7.0"
      (sources."finalhandler-0.5.0" // {
        dependencies = [
          sources."statuses-1.3.0"
          sources."unpipe-1.0.0"
        ];
      })
      sources."fresh-0.3.0"
      sources."merge-descriptors-1.0.1"
      sources."methods-1.1.2"
      (sources."on-finished-2.3.0" // {
        dependencies = [
          sources."ee-first-1.1.1"
        ];
      })
      sources."parseurl-1.3.1"
      sources."path-to-regexp-0.1.7"
      (sources."proxy-addr-1.1.2" // {
        dependencies = [
          sources."forwarded-0.1.0"
          sources."ipaddr.js-1.1.1"
        ];
      })
      sources."qs-6.2.0"
      sources."range-parser-1.2.0"
      (sources."send-0.14.1" // {
        dependencies = [
          sources."destroy-1.0.4"
          (sources."http-errors-1.5.0" // {
            dependencies = [
              sources."inherits-2.0.1"
              sources."setprototypeof-1.0.1"
            ];
          })
          sources."mime-1.3.4"
          sources."ms-0.7.1"
          sources."statuses-1.3.0"
        ];
      })
      sources."serve-static-1.11.1"
      (sources."type-is-1.6.13" // {
        dependencies = [
          sources."media-typer-0.3.0"
          (sources."mime-types-2.1.11" // {
            dependencies = [
              sources."mime-db-1.23.0"
            ];
          })
        ];
      })
      sources."utils-merge-1.0.0"
      sources."vary-1.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, unopinionated, minimalist web framework";
      homepage = http://expressjs.com/;
      license = "MIT";
    };
    production = true;
  };
  "nijs-svanderburg/nijs" = nodeEnv.buildNodePackage {
    name = "nijs";
    packageName = "nijs";
    version = "0.0.24";
    src = fetchgit {
      url = "git://github.com/svanderburg/nijs";
      rev = "2003ee7fa9d032e7803664414506224b86d16a9d";
      sha256 = "a88237615a9dfb41412a5a6b3e5868c7db72f1bd51cc71756a1f9d19f0d1d5ae";
    };
    dependencies = [
      sources."optparse-1.0.5"
      sources."slasp-0.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "An internal DSL for the Nix package manager in JavaScript";
      license = "MIT";
    };
    production = true;
  };
  "lodash-github:lodash/lodash" = nodeEnv.buildNodePackage {
    name = "lodash";
    packageName = "lodash";
    version = "4.16.0-pre";
    src = fetchgit {
      url = "git://github.com/lodash/lodash";
      rev = "d1abde7d1af1bb4cb2423286a54313220c0d8f31";
      sha256 = "0770f5a9aaf8fb13a3f6d2096bfa737d75f7ea735b39b70118b0e0767113d520";
    };
    buildInputs = globalBuildInputs;
    meta = {
      license = "MIT";
    };
    production = true;
  };
  "testb-./testb" = nodeEnv.buildNodePackage {
    name = "testb";
    packageName = "testb";
    version = "0.0.1";
    src = ./testb;
    dependencies = [
      sources."testa-../testa"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
  };
  es5-ext = nodeEnv.buildNodePackage {
    name = "es5-ext";
    packageName = "es5-ext";
    version = "0.10.12";
    src = fetchurl {
      url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.12.tgz";
      sha1 = "aa84641d4db76b62abba5e45fd805ecbab140047";
    };
    dependencies = [
      (sources."es6-iterator-2.0.0" // {
        dependencies = [
          sources."d-0.1.1"
          sources."es5-ext-0.10.12"
        ];
      })
      (sources."es6-symbol-3.1.0" // {
        dependencies = [
          sources."d-0.1.1"
          sources."es5-ext-0.10.12"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "ECMAScript extensions and shims";
      homepage = "https://github.com/medikoo/es5-ext#readme";
      license = "MIT";
    };
    production = true;
  };
  grunt-cli = nodeEnv.buildNodePackage {
    name = "grunt-cli";
    packageName = "grunt-cli";
    version = "1.2.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/grunt-cli/-/grunt-cli-1.2.0.tgz";
      sha1 = "562b119ebb069ddb464ace2845501be97b35b6a8";
    };
    dependencies = [
      (sources."findup-sync-0.3.0" // {
        dependencies = [
          (sources."glob-5.0.15" // {
            dependencies = [
              (sources."inflight-1.0.5" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."inherits-2.0.1"
              (sources."minimatch-3.0.3" // {
                dependencies = [
                  (sources."brace-expansion-1.1.6" // {
                    dependencies = [
                      sources."balanced-match-0.4.2"
                      sources."concat-map-0.0.1"
                    ];
                  })
                ];
              })
              (sources."once-1.3.3" // {
                dependencies = [
                  sources."wrappy-1.0.2"
                ];
              })
              sources."path-is-absolute-1.0.0"
            ];
          })
        ];
      })
      sources."grunt-known-options-1.1.0"
      (sources."nopt-3.0.6" // {
        dependencies = [
          sources."abbrev-1.0.9"
        ];
      })
      sources."resolve-1.1.7"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The grunt command line interface";
      homepage = "https://github.com/gruntjs/grunt-cli#readme";
      license = "MIT";
    };
    production = true;
  };
  bower = nodeEnv.buildNodePackage {
    name = "bower";
    packageName = "bower";
    version = "1.7.9";
    src = fetchurl {
      url = "https://registry.npmjs.org/bower/-/bower-1.7.9.tgz";
      sha1 = "b7296c2393e0d75edaa6ca39648132dd255812b0";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "The browser package manager";
      homepage = http://bower.io/;
      license = "MIT";
    };
    production = true;
  };
  coffee-script = nodeEnv.buildNodePackage {
    name = "coffee-script";
    packageName = "coffee-script";
    version = "1.10.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/coffee-script/-/coffee-script-1.10.0.tgz";
      sha1 = "12938bcf9be1948fa006f92e0c4c9e81705108c0";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Unfancy JavaScript";
      homepage = http://coffeescript.org/;
      license = "MIT";
    };
    production = true;
  };
  floomatic = nodeEnv.buildNodePackage {
    name = "floomatic";
    packageName = "floomatic";
    version = "0.5.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/floomatic/-/floomatic-0.5.3.tgz";
      sha1 = "d7a5aa8709300758d51f4de4be1f4e6fa1389050";
    };
    dependencies = [
      sources."async-1.5.2"
      sources."dmp-0.2.0"
      (sources."floorine-0.3.0" // {
        dependencies = [
          sources."strftime-0.9.2"
        ];
      })
      sources."lodash-4.15.0"
      (sources."minimatch-3.0.3" // {
        dependencies = [
          (sources."brace-expansion-1.1.6" // {
            dependencies = [
              sources."balanced-match-0.4.2"
              sources."concat-map-0.0.1"
            ];
          })
        ];
      })
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."open-0.0.5"
      (sources."optimist-0.6.1" // {
        dependencies = [
          sources."wordwrap-0.0.3"
          sources."minimist-0.0.10"
        ];
      })
      (sources."request-2.74.0" // {
        dependencies = [
          sources."aws-sign2-0.6.0"
          sources."aws4-1.4.1"
          (sources."bl-1.1.2" // {
            dependencies = [
              (sources."readable-stream-2.0.6" // {
                dependencies = [
                  sources."core-util-is-1.0.2"
                  sources."inherits-2.0.1"
                  sources."isarray-1.0.0"
                  sources."process-nextick-args-1.0.7"
                  sources."string_decoder-0.10.31"
                  sources."util-deprecate-1.0.2"
                ];
              })
            ];
          })
          sources."caseless-0.11.0"
          (sources."combined-stream-1.0.5" // {
            dependencies = [
              sources."delayed-stream-1.0.0"
            ];
          })
          sources."extend-3.0.0"
          sources."forever-agent-0.6.1"
          (sources."form-data-1.0.1" // {
            dependencies = [
              sources."async-2.0.1"
            ];
          })
          (sources."har-validator-2.0.6" // {
            dependencies = [
              (sources."chalk-1.1.3" // {
                dependencies = [
                  sources."ansi-styles-2.2.1"
                  sources."escape-string-regexp-1.0.5"
                  (sources."has-ansi-2.0.0" // {
                    dependencies = [
                      sources."ansi-regex-2.0.0"
                    ];
                  })
                  (sources."strip-ansi-3.0.1" // {
                    dependencies = [
                      sources."ansi-regex-2.0.0"
                    ];
                  })
                  sources."supports-color-2.0.0"
                ];
              })
              (sources."commander-2.9.0" // {
                dependencies = [
                  sources."graceful-readlink-1.0.1"
                ];
              })
              (sources."is-my-json-valid-2.13.1" // {
                dependencies = [
                  sources."generate-function-2.0.0"
                  (sources."generate-object-property-1.2.0" // {
                    dependencies = [
                      sources."is-property-1.0.2"
                    ];
                  })
                  sources."jsonpointer-2.0.0"
                  sources."xtend-4.0.1"
                ];
              })
              (sources."pinkie-promise-2.0.1" // {
                dependencies = [
                  sources."pinkie-2.0.4"
                ];
              })
            ];
          })
          (sources."hawk-3.1.3" // {
            dependencies = [
              sources."hoek-2.16.3"
              sources."boom-2.10.1"
              sources."cryptiles-2.0.5"
              sources."sntp-1.0.9"
            ];
          })
          (sources."http-signature-1.1.1" // {
            dependencies = [
              sources."assert-plus-0.2.0"
              (sources."jsprim-1.3.0" // {
                dependencies = [
                  sources."extsprintf-1.0.2"
                  sources."json-schema-0.2.2"
                  sources."verror-1.3.6"
                ];
              })
              (sources."sshpk-1.10.0" // {
                dependencies = [
                  sources."asn1-0.2.3"
                  sources."assert-plus-1.0.0"
                  sources."dashdash-1.14.0"
                  sources."getpass-0.1.6"
                  sources."jsbn-0.1.0"
                  sources."tweetnacl-0.13.3"
                  sources."jodid25519-1.0.2"
                  sources."ecc-jsbn-0.1.1"
                  (sources."bcrypt-pbkdf-1.0.0" // {
                    dependencies = [
                      sources."tweetnacl-0.14.3"
                    ];
                  })
                ];
              })
            ];
          })
          sources."is-typedarray-1.0.0"
          sources."isstream-0.1.2"
          sources."json-stringify-safe-5.0.1"
          (sources."mime-types-2.1.11" // {
            dependencies = [
              sources."mime-db-1.23.0"
            ];
          })
          sources."node-uuid-1.4.7"
          sources."oauth-sign-0.8.2"
          sources."qs-6.2.1"
          sources."stringstream-0.0.5"
          sources."tough-cookie-2.3.1"
          sources."tunnel-agent-0.4.3"
        ];
      })
      (sources."fsevents-1.0.14" // {
        dependencies = [
          sources."nan-2.4.0"
          (sources."node-pre-gyp-0.6.30" // {
            dependencies = [
              (sources."nopt-3.0.6" // {
                dependencies = [
                  sources."abbrev-1.0.9"
                ];
              })
              (sources."npmlog-4.0.0" // {
                dependencies = [
                  (sources."are-we-there-yet-1.1.2" // {
                    dependencies = [
                      sources."delegates-1.0.0"
                      (sources."readable-stream-2.1.5" // {
                        dependencies = [
                          sources."buffer-shims-1.0.0"
                          sources."core-util-is-1.0.2"
                          sources."inherits-2.0.1"
                          sources."isarray-1.0.0"
                          sources."process-nextick-args-1.0.7"
                          sources."string_decoder-0.10.31"
                          sources."util-deprecate-1.0.2"
                        ];
                      })
                    ];
                  })
                  sources."console-control-strings-1.1.0"
                  (sources."gauge-2.6.0" // {
                    dependencies = [
                      sources."aproba-1.0.4"
                      sources."has-color-0.1.7"
                      sources."has-unicode-2.0.1"
                      sources."object-assign-4.1.0"
                      sources."signal-exit-3.0.0"
                      (sources."string-width-1.0.2" // {
                        dependencies = [
                          (sources."code-point-at-1.0.0" // {
                            dependencies = [
                              sources."number-is-nan-1.0.0"
                            ];
                          })
                          (sources."is-fullwidth-code-point-1.0.0" // {
                            dependencies = [
                              sources."number-is-nan-1.0.0"
                            ];
                          })
                        ];
                      })
                      (sources."strip-ansi-3.0.1" // {
                        dependencies = [
                          sources."ansi-regex-2.0.0"
                        ];
                      })
                      sources."wide-align-1.1.0"
                    ];
                  })
                  sources."set-blocking-2.0.0"
                ];
              })
              (sources."rc-1.1.6" // {
                dependencies = [
                  sources."deep-extend-0.4.1"
                  sources."ini-1.3.4"
                  sources."minimist-1.2.0"
                  sources."strip-json-comments-1.0.4"
                ];
              })
              (sources."rimraf-2.5.4" // {
                dependencies = [
                  (sources."glob-7.0.6" // {
                    dependencies = [
                      sources."fs.realpath-1.0.0"
                      (sources."inflight-1.0.5" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      sources."inherits-2.0.1"
                      (sources."once-1.3.3" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      sources."path-is-absolute-1.0.0"
                    ];
                  })
                ];
              })
              sources."semver-5.3.0"
              (sources."tar-2.2.1" // {
                dependencies = [
                  sources."block-stream-0.0.9"
                  (sources."fstream-1.0.10" // {
                    dependencies = [
                      sources."graceful-fs-4.1.6"
                    ];
                  })
                  sources."inherits-2.0.1"
                ];
              })
              (sources."tar-pack-3.1.4" // {
                dependencies = [
                  (sources."debug-2.2.0" // {
                    dependencies = [
                      sources."ms-0.7.1"
                    ];
                  })
                  (sources."fstream-1.0.10" // {
                    dependencies = [
                      sources."graceful-fs-4.1.6"
                      sources."inherits-2.0.1"
                    ];
                  })
                  (sources."fstream-ignore-1.0.5" // {
                    dependencies = [
                      sources."inherits-2.0.1"
                    ];
                  })
                  (sources."once-1.3.3" // {
                    dependencies = [
                      sources."wrappy-1.0.2"
                    ];
                  })
                  (sources."readable-stream-2.1.5" // {
                    dependencies = [
                      sources."buffer-shims-1.0.0"
                      sources."core-util-is-1.0.2"
                      sources."inherits-2.0.1"
                      sources."isarray-1.0.0"
                      sources."process-nextick-args-1.0.7"
                      sources."string_decoder-0.10.31"
                      sources."util-deprecate-1.0.2"
                    ];
                  })
                  sources."uid-number-0.0.6"
                ];
              })
            ];
          })
        ];
      })
      sources."native-diff-match-patch-0.3.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A headless [Floobits](https://floobits.com/) workspace and disk watcher. Handy for shipping changes to a testing server.";
      homepage = https://github.com/Floobits/floomatic/;
      license = "Apache-2.0";
    };
    production = true;
  };
  "@sindresorhus/df" = nodeEnv.buildNodePackage {
    name = "_at_sindresorhus_slash_df";
    packageName = "@sindresorhus/df";
    version = "2.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@sindresorhus/df/-/df-2.1.0.tgz";
      sha1 = "d208cf27e06f0bb476d14d7deccd7d726e9aa389";
    };
    dependencies = [
      (sources."execa-0.2.2" // {
        dependencies = [
          (sources."cross-spawn-async-2.2.4" // {
            dependencies = [
              (sources."lru-cache-4.0.1" // {
                dependencies = [
                  sources."pseudomap-1.0.2"
                  sources."yallist-2.0.0"
                ];
              })
              (sources."which-1.2.10" // {
                dependencies = [
                  sources."isexe-1.1.2"
                ];
              })
            ];
          })
          sources."npm-run-path-1.0.0"
          sources."object-assign-4.1.0"
          sources."path-key-1.0.0"
          sources."strip-eof-1.0.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Get free disk space info from `df -kP`";
      homepage = "https://github.com/sindresorhus/df#readme";
      license = "MIT";
    };
    production = true;
  };
}